baseurl = "https://smwindecker.netlify.com/"
languageCode = "en-US"
title = "Saras Windecker"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain-modified"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Saras Windecker"
  description = "This is my research website."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "smwindecker"
  Twitter       = "smwindecker"

## Main Menu
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "CV"
  identifier = "CV"
  weight = 200
  url = "/CV/"
[[menu.main]]
  name = "projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "blog"
  weight = 400
  identifier = "blog"
  url = "/blog/"


